image: seifsabry/ci_cd_gcloud:v1

variables:
  GRADLE_USER_HOME: "cache/.gradle"
  GRADLE_ARGS_CI: "--no-daemon --stacktrace"

stages:
  - build
  - test
  - deploy
#  - destroy TODO: destroy the app after testing

before_script:
  - echo "Start CI/CD"
  - echo "The current directory is $(pwd)"

cache:
  paths:
    - $GRADLE_USER_HOME/wrapper/
    - $GRADLE_USER_HOME/caches/

build:
  stage: build
  script:
    - ./gradlew $GRADLE_ARGS_CI -g $GRADLE_USER_HOME assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  artifacts:
    expire_in: 1 week
    reports:
      junit: build/test-results/test/*.xml
    when: always
    paths:
      - build/reports/tests/test/index.html
  script:
    - ./gradlew $GRADLE_ARGS_CI -g $GRADLE_USER_HOME check

deploy:
  stage: deploy
  when: manual
  script:
    - echo $(gcloud --version)
    - gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT_FILE
    - gcloud app deploy app.yml --quiet --project $GOOGLE_PROJECT_ID
  only:
    - main

after_script:
  - echo "End CI/CD"
