variables:
  GRADLE_USER_HOME: "cache/.gradle"
  GRADLE_ARGS_CI: "--no-daemon --stacktrace"

stages:
  - build
  - test
  - deploy
  - destroy

before_script:
  - echo "Start CI/CD"
  - echo "The current directory is $(pwd)"

cache:
  paths:
    - $GRADLE_USER_HOME/wrapper/
    - $GRADLE_USER_HOME/caches/

build:
  image: gradle:7.2.0-jdk17
  stage: build
  script:
    - ./gradlew $GRADLE_ARGS_CI -g $GRADLE_USER_HOME assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  image: gradle:7.2.0-jdk17
  stage: test
  artifacts:
    expire_in: 1 week
    reports:
      junit: build/test-results/test/*.xml
    when: always
    paths:
      - build/reports/tests/test/index.html
  script:
    - ./gradlew $GRADLE_ARGS_CI -g $GRADLE_USER_HOME check

deploy:
  image: google/cloud-sdk:latest
  stage: deploy
  when: manual
  script:
    - echo $(gcloud --version)
    - echo $ENV_VARIABLES
    - gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT_FILE
    - chmod +x ./scripts/deploy.sh
    - ./scripts/deploy.sh $ENV_VARIABLES
#  only:
#    - main

destroy:
  stage: destroy
  when: manual
  script:
    - ./scripts/destroy.sh

after_script:
  - echo "End CI/CD"
