spring:
  mail:
#    host: smtp.gmail.com
#    port: ${DEV_EMAIL_PORT}
#    username: ${DEV_EMAIL_USERNAME}
#    password: ${DEV_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    database: HSQL
    show-sql: true
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:./db/testdb
    username: ""
    password: ""
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/javah
      additional-exclude: WEB-INF/**
  thymeleaf:
    cache: false
logging:
  level:
    #      web: debug
    be.kdg.finalproject: debug


