spring:
  mail:
    host: smtp.gmail.com
    port: ${DEV_EMAIL_PORT}
    username: ${DEV_EMAIL_USERNAME}
    password: ${DEV_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
    database: H2
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/javah
      additional-exclude: WEB-INF/**
  thymeleaf:
    cache: false
  sql:
    init:
#      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql
logging:
  level:
    #    web: debug
    be.kdg.finalproject: debug


