spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - address
          facebook:
            clientId: ${FACEBOOK_CLIENT_ID}
            clientSecret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: dev # prod, dev
  messages:
    basename: templates/details
server:
  port: 8080