spring:
  mail:
    #    host: smtp.gmail.com
    #    port: ${DEV_EMAIL_PORT}
    #    username: ${DEV_EMAIL_USERNAME}
    #    password: ${DEV_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
    database: POSTGRESQL
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/YouthCouncilDev
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/javah
      additional-exclude: WEB-INF/**
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always
#      data-locations: classpath:sql/municipalities/*.sql
logging:
  level:
    #    org:
    #      springframework:
    #        security: debug
    #        web: debug
    be.kdg.finalproject: debug