spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 4MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - address
          facebook:
            clientId: ${FACEBOOK_CLIENT_ID}
            clientSecret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: dev # prod, dev, devpsql
  messages:
    basename: templates/details
