spring:
  mail:
#    host: smtp.gmail.com
#    port: ${EMAIL_PORT}
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
    properties:
     mail:
        smtp:
        auth: true
        starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/YouthCouncil
    username: postgres
    password: ${POSTGRES_PASSWORD}
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**
  thymeleaf:
    cache: false
  messages:
    basename: templates/messages
