INSERT INTO municipalities (name) VALUES ('Antwerp');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2000, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2018, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2020, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2030, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2040, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2050, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2060, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2100, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2140, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2170, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2180, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2600, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2610, 1);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2660, 1);
INSERT INTO municipalities (name) VALUES ('Zwijndrecht');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2070, 2);
INSERT INTO municipalities (name) VALUES ('Wijnegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2110, 3);
INSERT INTO municipalities (name) VALUES ('Borsbeek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2150, 4);
INSERT INTO municipalities (name) VALUES ('Wommelgem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2160, 5);
INSERT INTO municipalities (name) VALUES ('Herentals');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2200, 6);
INSERT INTO municipalities (name) VALUES ('Heist-op-den-Berg');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2220, 7);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2221, 7);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2222, 7);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2223, 7);
INSERT INTO municipalities (name) VALUES ('Herselt');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2230, 8);
INSERT INTO municipalities (name) VALUES ('Hulshout');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2235, 9);
INSERT INTO municipalities (name) VALUES ('Zandhoven');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2240, 10);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2242, 10);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2243, 10);
INSERT INTO municipalities (name) VALUES ('Olen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2250, 11);
INSERT INTO municipalities (name) VALUES ('Westerlo');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2260, 12);
INSERT INTO municipalities (name) VALUES ('Herenthout');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2270, 13);
INSERT INTO municipalities (name) VALUES ('Lille');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2275, 14);
INSERT INTO municipalities (name) VALUES ('Grobbendonk');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2280, 15);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2288, 15);
INSERT INTO municipalities (name) VALUES ('Vorselaar');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2290, 16);
INSERT INTO municipalities (name) VALUES ('Turnhout');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2300, 17);
INSERT INTO municipalities (name) VALUES ('Rijkevorsel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2310, 18);
INSERT INTO municipalities (name) VALUES ('Hoogstraten');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2320, 19);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2321, 19);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2322, 19);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2323, 19);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2328, 19);
INSERT INTO municipalities (name) VALUES ('Merksplas');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2330, 20);
INSERT INTO municipalities (name) VALUES ('Beerse');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2340, 21);
INSERT INTO municipalities (name) VALUES ('Vosselaar');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2350, 22);
INSERT INTO municipalities (name) VALUES ('Oud-Turnhout');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2360, 23);
INSERT INTO municipalities (name) VALUES ('Arendonk');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2370, 24);
INSERT INTO municipalities (name) VALUES ('Ravels');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2380, 25);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2381, 25);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2382, 25);
INSERT INTO municipalities (name) VALUES ('Baerle-Duc');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2387, 26);
INSERT INTO municipalities (name) VALUES ('Malle');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2390, 27);
INSERT INTO municipalities (name) VALUES ('Mol');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2400, 28);
INSERT INTO municipalities (name) VALUES ('Laakdal');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2430, 29);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2431, 29);
INSERT INTO municipalities (name) VALUES ('Geel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2440, 30);
INSERT INTO municipalities (name) VALUES ('Meerhout');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2450, 31);
INSERT INTO municipalities (name) VALUES ('Kasterlee');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2460, 32);
INSERT INTO municipalities (name) VALUES ('Retie');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2470, 33);
INSERT INTO municipalities (name) VALUES ('Dessel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2480, 34);
INSERT INTO municipalities (name) VALUES ('Balen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2490, 35);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2491, 35);
INSERT INTO municipalities (name) VALUES ('Lierre');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2500, 36);
INSERT INTO municipalities (name) VALUES ('Ranst');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2520, 37);
INSERT INTO municipalities (name) VALUES ('Boechout');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2530, 38);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2531, 38);
INSERT INTO municipalities (name) VALUES ('Hove');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2540, 39);
INSERT INTO municipalities (name) VALUES ('Lint');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2547, 40);
INSERT INTO municipalities (name) VALUES ('Kontich');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2550, 41);
INSERT INTO municipalities (name) VALUES ('Nijlen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2560, 42);
INSERT INTO municipalities (name) VALUES ('Duffel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2570, 43);
INSERT INTO municipalities (name) VALUES ('Putte');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2580, 44);
INSERT INTO municipalities (name) VALUES ('Berlaar');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2590, 45);
INSERT INTO municipalities (name) VALUES ('Hemiksem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2620, 46);
INSERT INTO municipalities (name) VALUES ('Schelle');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2627, 47);
INSERT INTO municipalities (name) VALUES ('Aartselaar');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2630, 48);
INSERT INTO municipalities (name) VALUES ('Mortsel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2640, 49);
INSERT INTO municipalities (name) VALUES ('Edegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2650, 50);
INSERT INTO municipalities (name) VALUES ('Malines');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2800, 51);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2801, 51);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2811, 51);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2812, 51);
INSERT INTO municipalities (name) VALUES ('Bonheiden');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2820, 52);
INSERT INTO municipalities (name) VALUES ('Willebroek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2830, 53);
INSERT INTO municipalities (name) VALUES ('Rumst');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2840, 54);
INSERT INTO municipalities (name) VALUES ('Niel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2845, 55);
INSERT INTO municipalities (name) VALUES ('Boom');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2850, 56);
INSERT INTO municipalities (name) VALUES ('Sint-Katelijne-Waver');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2860, 57);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2861, 57);
INSERT INTO municipalities (name) VALUES ('Puurs-Sint-Amands');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2870, 58);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2890, 58);
INSERT INTO municipalities (name) VALUES ('Bornem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2880, 59);
INSERT INTO municipalities (name) VALUES ('Schoten');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2900, 60);
INSERT INTO municipalities (name) VALUES ('Essen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2910, 61);
INSERT INTO municipalities (name) VALUES ('Kalmthout');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2920, 62);
INSERT INTO municipalities (name) VALUES ('Brasschaat');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2930, 63);
INSERT INTO municipalities (name) VALUES ('Stabroek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2940, 64);
INSERT INTO municipalities (name) VALUES ('Kapellen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2950, 65);
INSERT INTO municipalities (name) VALUES ('Brecht');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2960, 66);
INSERT INTO municipalities (name) VALUES ('Schilde');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2970, 67);
INSERT INTO municipalities (name) VALUES ('Zoersel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2980, 68);
INSERT INTO municipalities (name) VALUES ('Wuustwezel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (2990, 69);
INSERT INTO municipalities (name) VALUES ('Gand');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9000, 70);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9030, 70);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9031, 70);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9032, 70);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9040, 70);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9041, 70);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9042, 70);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9050, 70);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9051, 70);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9052, 70);
INSERT INTO municipalities (name) VALUES ('Zelzate');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9060, 71);
INSERT INTO municipalities (name) VALUES ('Destelbergen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9070, 72);
INSERT INTO municipalities (name) VALUES ('Lochristi');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9080, 73);
INSERT INTO municipalities (name) VALUES ('Melle');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9090, 74);
INSERT INTO municipalities (name) VALUES ('Saint-Nicolas');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9100, 75);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9111, 75);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9112, 75);
INSERT INTO municipalities (name) VALUES ('Beveren');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9120, 76);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9130, 76);
INSERT INTO municipalities (name) VALUES ('Tamise');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9140, 77);
INSERT INTO municipalities (name) VALUES ('Kruibeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9150, 78);
INSERT INTO municipalities (name) VALUES ('Lokeren');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9160, 79);
INSERT INTO municipalities (name) VALUES ('Sint-Gillis-Waas');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9170, 80);
INSERT INTO municipalities (name) VALUES ('Moerbeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9180, 81);
INSERT INTO municipalities (name) VALUES ('Wachtebeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9185, 82);
INSERT INTO municipalities (name) VALUES ('Stekene');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9190, 83);
INSERT INTO municipalities (name) VALUES ('Termonde');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9200, 84);
INSERT INTO municipalities (name) VALUES ('Hamme');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9220, 85);
INSERT INTO municipalities (name) VALUES ('Wetteren');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9230, 86);
INSERT INTO municipalities (name) VALUES ('Zele');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9240, 87);
INSERT INTO municipalities (name) VALUES ('Waasmunster');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9250, 88);
INSERT INTO municipalities (name) VALUES ('Buggenhout');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9255, 89);
INSERT INTO municipalities (name) VALUES ('Wichelen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9260, 90);
INSERT INTO municipalities (name) VALUES ('Laarne');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9270, 91);
INSERT INTO municipalities (name) VALUES ('Lebbeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9280, 92);
INSERT INTO municipalities (name) VALUES ('Berlare');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9290, 93);
INSERT INTO municipalities (name) VALUES ('Alost');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9300, 94);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9308, 94);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9310, 94);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9320, 94);
INSERT INTO municipalities (name) VALUES ('Lede');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9340, 95);
INSERT INTO municipalities (name) VALUES ('Ninove');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9400, 96);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9401, 96);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9402, 96);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9403, 96);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9404, 96);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9406, 96);
INSERT INTO municipalities (name) VALUES ('Erpe-Mere');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9420, 97);
INSERT INTO municipalities (name) VALUES ('Haaltert');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9450, 98);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9451, 98);
INSERT INTO municipalities (name) VALUES ('Denderleeuw');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9470, 99);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9472, 99);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9473, 99);
INSERT INTO municipalities (name) VALUES ('Grammont');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9500, 100);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9506, 100);
INSERT INTO municipalities (name) VALUES ('Sint-Lievens-Houtem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9520, 101);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9521, 101);
INSERT INTO municipalities (name) VALUES ('Herzele');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9550, 102);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9551, 102);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9552, 102);
INSERT INTO municipalities (name) VALUES ('Lierde');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9570, 103);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9571, 103);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9572, 103);
INSERT INTO municipalities (name) VALUES ('Renaix');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9600, 104);
INSERT INTO municipalities (name) VALUES ('Zottegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9620, 105);
INSERT INTO municipalities (name) VALUES ('Zwalin');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9630, 106);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9636, 106);
INSERT INTO municipalities (name) VALUES ('Brakel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9660, 107);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9661, 107);
INSERT INTO municipalities (name) VALUES ('Horebeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9667, 108);
INSERT INTO municipalities (name) VALUES ('Maarkedal');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9680, 109);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9681, 109);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9688, 109);
INSERT INTO municipalities (name) VALUES ('Kluisbergen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9690, 110);
INSERT INTO municipalities (name) VALUES ('Audenarde');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9700, 111);
INSERT INTO municipalities (name) VALUES ('Kruisem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9750, 112);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9770, 112);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9771, 112);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9772, 112);
INSERT INTO municipalities (name) VALUES ('Wortegem-Petegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9790, 113);
INSERT INTO municipalities (name) VALUES ('Deinze');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9800, 114);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9850, 114);
INSERT INTO municipalities (name) VALUES ('Nazareth');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9810, 115);
INSERT INTO municipalities (name) VALUES ('Merelbeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9820, 116);
INSERT INTO municipalities (name) VALUES ('Sint-Martens-Latem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9830, 117);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9831, 117);
INSERT INTO municipalities (name) VALUES ('De Pinte');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9840, 118);
INSERT INTO municipalities (name) VALUES ('Oosterzele');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9860, 119);
INSERT INTO municipalities (name) VALUES ('Zulte');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9870, 120);
INSERT INTO municipalities (name) VALUES ('Aalter');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9880, 121);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9881, 121);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9910, 121);
INSERT INTO municipalities (name) VALUES ('Gavere');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9890, 122);
INSERT INTO municipalities (name) VALUES ('Eeklo');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9900, 123);
INSERT INTO municipalities (name) VALUES ('Lievegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9920, 124);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9921, 124);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9930, 124);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9931, 124);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9932, 124);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9950, 124);
INSERT INTO municipalities (name) VALUES ('Evergem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9940, 125);
INSERT INTO municipalities (name) VALUES ('Assenede');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9960, 126);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9961, 126);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9968, 126);
INSERT INTO municipalities (name) VALUES ('Kaprijke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9970, 127);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9971, 127);
INSERT INTO municipalities (name) VALUES ('Sint-Laureins');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9980, 128);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9981, 128);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9982, 128);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9988, 128);
INSERT INTO municipalities (name) VALUES ('Maldegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9990, 129);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9991, 129);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (9992, 129);
INSERT INTO municipalities (name) VALUES ('Hal');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1500, 130);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1501, 130);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1502, 130);
INSERT INTO municipalities (name) VALUES ('Herne');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1540, 131);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1541, 131);
INSERT INTO municipalities (name) VALUES ('Biévène');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1547, 132);
INSERT INTO municipalities (name) VALUES ('Hoeilaart');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1560, 133);
INSERT INTO municipalities (name) VALUES ('Gammerages');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1570, 134);
INSERT INTO municipalities (name) VALUES ('Sint-Pieters-Leeuw');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1600, 135);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1601, 135);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1602, 135);
INSERT INTO municipalities (name) VALUES ('Drogenbos');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1620, 136);
INSERT INTO municipalities (name) VALUES ('Linkebeek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1630, 137);
INSERT INTO municipalities (name) VALUES ('Rhode-Saint-Genèse');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1640, 138);
INSERT INTO municipalities (name) VALUES ('Beersel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1650, 139);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1651, 139);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1652, 139);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1653, 139);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1654, 139);
INSERT INTO municipalities (name) VALUES ('Pepingen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1670, 140);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1671, 140);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1673, 140);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1674, 140);
INSERT INTO municipalities (name) VALUES ('Dilbeek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1700, 141);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1701, 141);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1702, 141);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1703, 141);
INSERT INTO municipalities (name) VALUES ('Asse');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1730, 142);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1731, 142);
INSERT INTO municipalities (name) VALUES ('Ternat');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1740, 143);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1741, 143);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1742, 143);
INSERT INTO municipalities (name) VALUES ('Opwijk');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1745, 144);
INSERT INTO municipalities (name) VALUES ('Lennik');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1750, 145);
INSERT INTO municipalities (name) VALUES ('Gooik');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1755, 146);
INSERT INTO municipalities (name) VALUES ('Roosdaal');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1760, 147);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1761, 147);
INSERT INTO municipalities (name) VALUES ('Liedekerke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1770, 148);
INSERT INTO municipalities (name) VALUES ('Wemmel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1780, 149);
INSERT INTO municipalities (name) VALUES ('Merchtem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1785, 150);
INSERT INTO municipalities (name) VALUES ('Affligem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1790, 151);
INSERT INTO municipalities (name) VALUES ('Vilvorde');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1800, 152);
INSERT INTO municipalities (name) VALUES ('Steenokkerzeel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1820, 153);
INSERT INTO municipalities (name) VALUES ('Machelen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1830, 154);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1831, 154);
INSERT INTO municipalities (name) VALUES ('Londerzeel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1840, 155);
INSERT INTO municipalities (name) VALUES ('Grimbergen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1850, 156);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1851, 156);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1852, 156);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1853, 156);
INSERT INTO municipalities (name) VALUES ('Meise');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1860, 157);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1861, 157);
INSERT INTO municipalities (name) VALUES ('Kapelle-op-den-Bos');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1880, 158);
INSERT INTO municipalities (name) VALUES ('Kampenhout');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1910, 159);
INSERT INTO municipalities (name) VALUES ('Zaventem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1930, 160);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1932, 160);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1933, 160);
INSERT INTO municipalities (name) VALUES ('Kraainem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1950, 161);
INSERT INTO municipalities (name) VALUES ('Wezembeek-Oppem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1970, 162);
INSERT INTO municipalities (name) VALUES ('Zemst');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1980, 163);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1981, 163);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (1982, 163);
INSERT INTO municipalities (name) VALUES ('Louvain');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3000, 164);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3001, 164);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3010, 164);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3012, 164);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3018, 164);
INSERT INTO municipalities (name) VALUES ('Herent');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3020, 165);
INSERT INTO municipalities (name) VALUES ('Huldenberg');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3040, 166);
INSERT INTO municipalities (name) VALUES ('Oud-Heverlee');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3050, 167);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3051, 167);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3052, 167);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3053, 167);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3054, 167);
INSERT INTO municipalities (name) VALUES ('Bertem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3060, 168);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3061, 168);
INSERT INTO municipalities (name) VALUES ('Kortenberg');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3070, 169);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3071, 169);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3078, 169);
INSERT INTO municipalities (name) VALUES ('Tervuren');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3080, 170);
INSERT INTO municipalities (name) VALUES ('Overijse');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3090, 171);
INSERT INTO municipalities (name) VALUES ('Rotselaar');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3110, 172);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3111, 172);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3118, 172);
INSERT INTO municipalities (name) VALUES ('Tremelo');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3120, 173);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3128, 173);
INSERT INTO municipalities (name) VALUES ('Begijnendijk');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3130, 174);
INSERT INTO municipalities (name) VALUES ('Keerbergen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3140, 175);
INSERT INTO municipalities (name) VALUES ('Haacht');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3150, 176);
INSERT INTO municipalities (name) VALUES ('Boortmeerbeek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3190, 177);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3191, 177);
INSERT INTO municipalities (name) VALUES ('Aarschot');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3200, 178);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3201, 178);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3202, 178);
INSERT INTO municipalities (name) VALUES ('Lubbeek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3210, 179);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3211, 179);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3212, 179);
INSERT INTO municipalities (name) VALUES ('Holsbeek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3220, 180);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3221, 180);
INSERT INTO municipalities (name) VALUES ('Montaigu-Zichem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3270, 181);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3271, 181);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3272, 181);
INSERT INTO municipalities (name) VALUES ('Diest');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3290, 182);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3293, 182);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3294, 182);
INSERT INTO municipalities (name) VALUES ('Tirlemont');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3300, 183);
INSERT INTO municipalities (name) VALUES ('Hoegaarden');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3320, 184);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3321, 184);
INSERT INTO municipalities (name) VALUES ('Linter');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3350, 185);
INSERT INTO municipalities (name) VALUES ('Bierbeek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3360, 186);
INSERT INTO municipalities (name) VALUES ('Boutersem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3370, 187);
INSERT INTO municipalities (name) VALUES ('Glabbeek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3380, 188);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3381, 188);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3384, 188);
INSERT INTO municipalities (name) VALUES ('Tielt-Winge');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3390, 189);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3391, 189);
INSERT INTO municipalities (name) VALUES ('Landen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3400, 190);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3401, 190);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3404, 190);
INSERT INTO municipalities (name) VALUES ('Léau');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3440, 191);
INSERT INTO municipalities (name) VALUES ('Geetbets');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3450, 192);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3454, 192);
INSERT INTO municipalities (name) VALUES ('Bekkevoort');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3460, 193);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3461, 193);
INSERT INTO municipalities (name) VALUES ('Kortenaken');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3470, 194);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3471, 194);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3472, 194);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3473, 194);
INSERT INTO municipalities (name) VALUES ('Hasselt');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3500, 195);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3501, 195);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3510, 195);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3511, 195);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3512, 195);
INSERT INTO municipalities (name) VALUES ('Zonhoven');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3520, 196);
INSERT INTO municipalities (name) VALUES ('Houthalen-Helchteren');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3530, 197);
INSERT INTO municipalities (name) VALUES ('Herck-la-Ville');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3540, 198);
INSERT INTO municipalities (name) VALUES ('Halen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3545, 199);
INSERT INTO municipalities (name) VALUES ('Heusden-Zolder');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3550, 200);
INSERT INTO municipalities (name) VALUES ('Lummen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3560, 201);
INSERT INTO municipalities (name) VALUES ('Alken');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3570, 202);
INSERT INTO municipalities (name) VALUES ('Beringen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3580, 203);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3581, 203);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3582, 203);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3583, 203);
INSERT INTO municipalities (name) VALUES ('Diepenbeek');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3590, 204);
INSERT INTO municipalities (name) VALUES ('Genk');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3600, 205);
INSERT INTO municipalities (name) VALUES ('Lanaken');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3620, 206);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3621, 206);
INSERT INTO municipalities (name) VALUES ('Maasmechelen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3630, 207);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3631, 207);
INSERT INTO municipalities (name) VALUES ('Kinrooi');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3640, 208);
INSERT INTO municipalities (name) VALUES ('Dilsen-Stokkem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3650, 209);
INSERT INTO municipalities (name) VALUES ('Oudsbergen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3660, 210);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3670, 210);
INSERT INTO municipalities (name) VALUES ('As');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3665, 211);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3668, 211);
INSERT INTO municipalities (name) VALUES ('Maaseik');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3680, 212);
INSERT INTO municipalities (name) VALUES ('Zutendaal');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3690, 213);
INSERT INTO municipalities (name) VALUES ('Tongres');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3700, 214);
INSERT INTO municipalities (name) VALUES ('Herstappe');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3717, 215);
INSERT INTO municipalities (name) VALUES ('Kortessem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3720, 216);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3721, 216);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3722, 216);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3723, 216);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3724, 216);
INSERT INTO municipalities (name) VALUES ('Hoeselt');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3730, 217);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3732, 217);
INSERT INTO municipalities (name) VALUES ('Bilzen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3740, 218);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3742, 218);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3746, 218);
INSERT INTO municipalities (name) VALUES ('Riemst');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3770, 219);
INSERT INTO municipalities (name) VALUES ('Fourons');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3790, 220);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3791, 220);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3792, 220);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3793, 220);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3798, 220);
INSERT INTO municipalities (name) VALUES ('Saint-Trond');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3800, 221);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3803, 221);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3806, 221);
INSERT INTO municipalities (name) VALUES ('Wellen');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3830, 222);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3831, 222);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3832, 222);
INSERT INTO municipalities (name) VALUES ('Looz');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3840, 223);
INSERT INTO municipalities (name) VALUES ('Nieuwerkerken');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3850, 224);
INSERT INTO municipalities (name) VALUES ('Heers');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3870, 225);
INSERT INTO municipalities (name) VALUES ('Gingelom');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3890, 226);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3891, 226);
INSERT INTO municipalities (name) VALUES ('Pelt');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3900, 227);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3910, 227);
INSERT INTO municipalities (name) VALUES ('Lommel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3920, 228);
INSERT INTO municipalities (name) VALUES ('Hamont-Achel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3930, 229);
INSERT INTO municipalities (name) VALUES ('Hechtel-Eksel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3940, 230);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3941, 230);
INSERT INTO municipalities (name) VALUES ('Ham');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3945, 231);
INSERT INTO municipalities (name) VALUES ('Bocholt');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3950, 232);
INSERT INTO municipalities (name) VALUES ('Bree');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3960, 233);
INSERT INTO municipalities (name) VALUES ('Bourg-Léopold');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3970, 234);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3971, 234);
INSERT INTO municipalities (name) VALUES ('Tessenderlo');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3980, 235);
INSERT INTO municipalities (name) VALUES ('Peer');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (3990, 236);
INSERT INTO municipalities (name) VALUES ('Bruges');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8000, 237);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8200, 237);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8310, 237);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8380, 237);
INSERT INTO municipalities (name) VALUES ('Oostkamp');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8020, 238);
INSERT INTO municipalities (name) VALUES ('Zedelgem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8210, 239);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8211, 239);
INSERT INTO municipalities (name) VALUES ('Knokke-Heist');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8300, 240);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8301, 240);
INSERT INTO municipalities (name) VALUES ('Damme');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8340, 241);
INSERT INTO municipalities (name) VALUES ('Blankenberge');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8370, 242);
INSERT INTO municipalities (name) VALUES ('Zuienkerke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8377, 243);
INSERT INTO municipalities (name) VALUES ('Ostende');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8400, 244);
INSERT INTO municipalities (name) VALUES ('De Haan');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8420, 245);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8421, 245);
INSERT INTO municipalities (name) VALUES ('Middelkerke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8430, 246);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8431, 246);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8432, 246);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8433, 246);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8434, 246);
INSERT INTO municipalities (name) VALUES ('Bredene');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8450, 247);
INSERT INTO municipalities (name) VALUES ('Oudenburg');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8460, 248);
INSERT INTO municipalities (name) VALUES ('Gistel');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8470, 249);
INSERT INTO municipalities (name) VALUES ('Ichtegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8480, 250);
INSERT INTO municipalities (name) VALUES ('Jabbeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8490, 251);
INSERT INTO municipalities (name) VALUES ('Courtrai');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8500, 252);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8501, 252);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8510, 252);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8511, 252);
INSERT INTO municipalities (name) VALUES ('Kuurne');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8520, 253);
INSERT INTO municipalities (name) VALUES ('Harelbeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8530, 254);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8531, 254);
INSERT INTO municipalities (name) VALUES ('Deerlijk');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8540, 255);
INSERT INTO municipalities (name) VALUES ('Zwevegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8550, 256);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8551, 256);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8552, 256);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8553, 256);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8554, 256);
INSERT INTO municipalities (name) VALUES ('Wevelgem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8560, 257);
INSERT INTO municipalities (name) VALUES ('Anzegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8570, 258);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8572, 258);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8573, 258);
INSERT INTO municipalities (name) VALUES ('Avelgem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8580, 259);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8581, 259);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8582, 259);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8583, 259);
INSERT INTO municipalities (name) VALUES ('Espierres-Helchin');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8587, 260);
INSERT INTO municipalities (name) VALUES ('Dixmude');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8600, 261);
INSERT INTO municipalities (name) VALUES ('Kortemark');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8610, 262);
INSERT INTO municipalities (name) VALUES ('Nieuport');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8620, 263);
INSERT INTO municipalities (name) VALUES ('Furnes');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8630, 264);
INSERT INTO municipalities (name) VALUES ('Vleteren');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8640, 265);
INSERT INTO municipalities (name) VALUES ('Lo-Reninge');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8647, 266);
INSERT INTO municipalities (name) VALUES ('Houthulst');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8650, 267);
INSERT INTO municipalities (name) VALUES ('La Panne');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8660, 268);
INSERT INTO municipalities (name) VALUES ('Koksijde');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8670, 269);
INSERT INTO municipalities (name) VALUES ('Koekelare');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8680, 270);
INSERT INTO municipalities (name) VALUES ('Alveringem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8690, 271);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8691, 271);
INSERT INTO municipalities (name) VALUES ('Tielt');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8700, 272);
INSERT INTO municipalities (name) VALUES ('Wielsbeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8710, 273);
INSERT INTO municipalities (name) VALUES ('Dentergem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8720, 274);
INSERT INTO municipalities (name) VALUES ('Beernem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8730, 275);
INSERT INTO municipalities (name) VALUES ('Pittem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8740, 276);
INSERT INTO municipalities (name) VALUES ('Wingene');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8750, 277);
INSERT INTO municipalities (name) VALUES ('Ruiselede');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8755, 278);
INSERT INTO municipalities (name) VALUES ('Meulebeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8760, 279);
INSERT INTO municipalities (name) VALUES ('Ingelmunster');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8770, 280);
INSERT INTO municipalities (name) VALUES ('Oostrozebeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8780, 281);
INSERT INTO municipalities (name) VALUES ('Waregem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8790, 282);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8791, 282);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8792, 282);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8793, 282);
INSERT INTO municipalities (name) VALUES ('Roulers');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8800, 283);
INSERT INTO municipalities (name) VALUES ('Lichtervelde');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8810, 284);
INSERT INTO municipalities (name) VALUES ('Torhout');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8820, 285);
INSERT INTO municipalities (name) VALUES ('Hooglede');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8830, 286);
INSERT INTO municipalities (name) VALUES ('Staden');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8840, 287);
INSERT INTO municipalities (name) VALUES ('Ardooie');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8850, 288);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8851, 288);
INSERT INTO municipalities (name) VALUES ('Lendelede');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8860, 289);
INSERT INTO municipalities (name) VALUES ('Izegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8870, 290);
INSERT INTO municipalities (name) VALUES ('Ledegem');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8880, 291);
INSERT INTO municipalities (name) VALUES ('Moorslede');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8890, 292);
INSERT INTO municipalities (name) VALUES ('Ypres');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8900, 293);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8902, 293);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8904, 293);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8906, 293);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8908, 293);
INSERT INTO municipalities (name) VALUES ('Langemark-Poelkapelle');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8920, 294);
INSERT INTO municipalities (name) VALUES ('Menin');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8930, 295);
INSERT INTO municipalities (name) VALUES ('Wervik');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8940, 296);
INSERT INTO municipalities (name) VALUES ('Heuvelland');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8950, 297);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8951, 297);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8952, 297);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8953, 297);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8954, 297);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8956, 297);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8958, 297);
INSERT INTO municipalities (name) VALUES ('Messines');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8957, 298);
INSERT INTO municipalities (name) VALUES ('Poperinge');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8970, 299);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8972, 299);
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8978, 299);
INSERT INTO municipalities (name) VALUES ('Zonnebeke');
INSERT INTO postcodes (postcode_id, municipality_id) VALUES (8980, 300);

